"""
PDF generation for quiz sheets
Creates PDF with quiz on left, answers on right
"""

from pathlib import Path
from typing import Dict, List
from datetime import datetime

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.pdfgen import canvas
    from reportlab.lib import colors
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
except ImportError:
    canvas = None

from config import Config


class PDFGenerator:
    """Generates PDF quiz sheets with answers"""

    def __init__(self, config: Config):
        self.config = config

        if canvas is None:
            raise ImportError("reportlab not installed. Install with: pip install reportlab")

    def create_quiz_pdf(
        self,
        quiz_data: dict,
        output_path: Path,
        quiz_name: str,
        quiz_style: str = "Split Page"
    ):
        """
        Create a PDF quiz sheet

        Args:
            quiz_data: Quiz content from LLM
            output_path: Where to save PDF
            quiz_name: Name of the quiz
            quiz_style: Layout style ("Split Page" or "Full Page")
        """
        # Ensure output directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

        if quiz_style == "Full Page":
            self._create_full_page_quiz(quiz_data, output_path, quiz_name)
        else:
            self._create_split_page_quiz(quiz_data, output_path, quiz_name)

    def _create_split_page_quiz(
        self,
        quiz_data: dict,
        output_path: Path,
        quiz_name: str
    ):
        """Create a split-page quiz (quiz on left, answers on right)"""
        # Create canvas
        c = canvas.Canvas(str(output_path), pagesize=letter)
        width, height = letter

        # Set up fonts
        c.setFont("Helvetica", 12)

        # Margins
        margin = 0.5 * inch
        center_x = width / 2

        # Starting Y position
        y_pos = height - margin

        # Title
        title = quiz_data.get("quiz_title", quiz_name)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(margin, y_pos, title)
        y_pos -= 30

        # Draw center line
        c.setStrokeColor(colors.lightgrey)
        c.setLineWidth(0.5)
        c.line(center_x, margin, center_x, height - margin)

        # Quiz section label
        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin, y_pos, "QUIZ")
        c.drawString(center_x + 10, y_pos, "ANSWERS")
        y_pos -= 20

        # Reset to normal font
        c.setFont("Helvetica", 12)

        # Process questions
        questions = quiz_data.get("questions", [])
        question_num = 1

        for q in questions:
            # Check if we need a new page
            if y_pos < margin + 50:
                c.showPage()
                y_pos = height - margin
                c.setFont("Helvetica", 12)

                # Redraw center line on new page
                c.setStrokeColor(colors.lightgrey)
                c.setLineWidth(0.5)
                c.line(center_x, margin, center_x, height - margin)
                c.setStrokeColor(colors.black)

            # Quiz text (left side)
            quiz_text = f"{question_num}. {q['text']}"

            # Word wrap for left side
            left_width = center_x - margin - 10
            wrapped_quiz = self._wrap_text(quiz_text, left_width, c)

            # Draw quiz questions
            quiz_y = y_pos
            for line in wrapped_quiz:
                c.drawString(margin, quiz_y, line)
                quiz_y -= 15

            # Answer (right side)
            answer_text = q['answer']
            c.drawString(center_x + 10, y_pos, answer_text)

            # Move to next question
            y_pos = quiz_y - 10
            question_num += 1

        # Footer
        c.setFont("Helvetica", 8)
        footer_text = f"Generated by QuizLM on {datetime.now().strftime('%Y-%m-%d')}"
        c.drawString(margin, margin - 20, footer_text)

        # Save PDF
        c.save()

    def _create_full_page_quiz(
        self,
        quiz_data: dict,
        output_path: Path,
        quiz_name: str
    ):
        """Create a full-page quiz with answers on separate pages at the end"""
        # Create canvas
        c = canvas.Canvas(str(output_path), pagesize=letter)
        width, height = letter

        # Set up fonts
        c.setFont("Helvetica", 12)

        # Margins
        margin = 0.5 * inch
        full_width = width - (2 * margin)

        # Starting Y position
        y_pos = height - margin

        # Title
        title = quiz_data.get("quiz_title", quiz_name)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(margin, y_pos, title)
        y_pos -= 30

        # Quiz section label
        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin, y_pos, "QUIZ")
        y_pos -= 20

        # Reset to normal font
        c.setFont("Helvetica", 12)

        # Process questions (quiz only)
        questions = quiz_data.get("questions", [])
        question_num = 1

        for q in questions:
            # Check if we need a new page
            if y_pos < margin + 50:
                c.showPage()
                y_pos = height - margin
                c.setFont("Helvetica", 12)

            # Quiz text (full width)
            quiz_text = f"{question_num}. {q['text']}"

            # Word wrap for full width
            wrapped_quiz = self._wrap_text(quiz_text, full_width, c)

            # Draw quiz questions
            for line in wrapped_quiz:
                c.drawString(margin, y_pos, line)
                y_pos -= 15

            # Extra spacing between questions
            y_pos -= 10
            question_num += 1

        # Footer on quiz pages
        c.setFont("Helvetica", 8)
        footer_text = f"Generated by QuizLM on {datetime.now().strftime('%Y-%m-%d')}"
        c.drawString(margin, margin - 20, footer_text)

        # Start answer key on new page
        c.showPage()
        y_pos = height - margin

        # Answer key title
        c.setFont("Helvetica-Bold", 14)
        c.drawString(margin, y_pos, "ANSWER KEY")
        y_pos -= 30

        # Reset to normal font
        c.setFont("Helvetica", 12)

        # List answers with padding for readability
        question_num = 1
        for q in questions:
            # Check if we need a new page
            if y_pos < margin + 30:
                c.showPage()
                y_pos = height - margin
                c.setFont("Helvetica", 12)

            # Format: "1. ____ answer ____"
            answer_text = f"{question_num}.    {q['answer']}"
            c.drawString(margin, y_pos, answer_text)
            y_pos -= 20
            question_num += 1

        # Footer on answer page
        c.setFont("Helvetica", 8)
        c.drawString(margin, margin - 20, footer_text)

        # Save PDF
        c.save()

    def _wrap_text(self, text: str, max_width: float, canvas_obj) -> List[str]:
        """Wrap text to fit within max_width"""
        words = text.split()
        lines = []
        current_line = []

        for word in words:
            test_line = ' '.join(current_line + [word])
            text_width = canvas_obj.stringWidth(test_line, "Helvetica", 12)

            if text_width <= max_width:
                current_line.append(word)
            else:
                if current_line:
                    lines.append(' '.join(current_line))
                current_line = [word]

        if current_line:
            lines.append(' '.join(current_line))

        return lines

